module.exports = {
  url: "https://www.supremewarrior.ph",
  name: "Supreme Warrior",
  buildDate: new Date().toISOString().slice(0, 10),
  blogPageSize: 15,
  staticPaths: [
    "/",
    "/enquiry/",
    "/enquiry-thank-you/",
    "/rfp/",
    "/rfp-thank-you/",
    "/sw-phys-mobile-patrol/",
    "/sw-phys-k9-security/",
    "/sw-phys-loss-prevention/",
    "/sw-phys-event-security/",
    "/sw-cyber-vciso/",
    "/sw-cyber-compliance/",
    "/sw-cyber-penetration-testing/",
    "/sw-cyber-security-operations/",
    "/sw-cyber-privacy/",
    "/sw-cyber-government-defense/",
  ],
};
